title: Mann Khor's Resume
author: Mann Khor
email: mannhingkhor@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome - my name is Mann and I'm a product manager @ Points. We build products for loyalty programs such as Emirates, United Airlines and Virgin Atlantic to name a few.
  mann khor resume

# social links
github_username:  rariducian

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
